spring:
  application:
    name: Sandbox
  profiles:
    active: prod
---
yaml:
  name: Sandbox-PROD
  environment: production
  enabled: true
  servers:
    - www.localhost.com
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  #    show-sql: false
# ===============================
# DATABASE PROPERTIES
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: admin
# ===============================
# Swagger UI
# ===============================
springdoc:
  swagger-ui:
    path: /swagger-ui.html
---
# Test properties and other environments below

